作業目標：<br>
熟悉邏輯運算<br>

作業重點：<br>
五大類邏輯函式與其對應的函式操作

題目：<br>
english_score = np.array([55,89,76,65,48,70])<br>
math_score = np.array([60,85,60,68,55,60])<br>
chinese_score = np.array([65,90,82,72,66,77])<br>
上3列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，運用上列數據回答下列問題。<br>
1. 有多少學生英文成績比數學成績高?
2. 是否全班同學最高分都是國文?

In [12]:
import numpy as np

english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,55,60])
chinese_score = np.array([65,90,82,72,66,77])

In [13]:
#1.有多少學生英文成績比數學成績高?
np.sum(np.greater(english_score, math_score))

3

In [48]:
#2.是否全班同學最高分都是國文?

## 合併所有科目，並找出所有人的最高分數
total_scores = np.vstack((english_score, math_score, chinese_score))
print('每個人的所有科目分數：\n', total_scores)

max_score = total.max(0)
print('每個人所有科目最高分數：\n', max_score)

## 01
## 判斷每個人的最高分是否為國文
highest_score_is_chinese = np.logical_and(max_score, chinese_score)
print('每個人最高分科目是否為國文？\n', highest_score_is_chinese)

## 判斷全班同學最高分是否都是國文
print('判斷全班同學最高分是否都是國文？（方法一）')
np.all(highest_score_is_chinese)

每個人的所有科目分數：
 [[55 89 76 65 48 70]
 [60 85 60 68 55 60]
 [65 90 82 72 66 77]]
每個人所有科目最高分數：
 [65 90 82 72 66 77]
每個人最高分科目是否為國文？
 [ True  True  True  True  True  True]
判斷全班同學最高分是否都是國文？（方法一）


True

In [65]:
## 02
print('判斷全班同學最高分是否都是國文？（方法二）')
np.array_equal(max_score, chinese_score)

判斷全班同學最高分是否都是國文？（方法二）


True